name: HolyTeams
version: '1.0-SNAPSHOT'
main: la.burden.holyteams.HolyTeams
commands:
  holyteams:
    description: Main command for HolyTeams
    usage: /<command>
    aliases: [ht]
  team:
    description: Team command
    usage: /<command>
    aliases: [t]